//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srcrepair.gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebugStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("srcrepair.gui.DebugStrings", typeof(DebugStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during unpacking files from a Zip archive..
        /// </summary>
        internal static string AppDbgExArWrkUnpack {
            get {
                return ResourceManager.GetString("AppDbgExArWrkUnpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove selected backups..
        /// </summary>
        internal static string AppDbgExBackupRem {
            get {
                return ResourceManager.GetString("AppDbgExBackupRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to restore a backup file..
        /// </summary>
        internal static string AppDbgExBackUpRestore {
            get {
                return ResourceManager.GetString("AppDbgExBackUpRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while checking for updates during application startup..
        /// </summary>
        internal static string AppDbgExBgWChk {
            get {
                return ResourceManager.GetString("AppDbgExBgWChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to backup all Steam settings stored in the registry..
        /// </summary>
        internal static string AppDbgExBkAllStm {
            get {
                return ResourceManager.GetString("AppDbgExBkAllStm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to load the backup file into the selected text editor..
        /// </summary>
        internal static string AppDbgExBkExtEdt {
            get {
                return ResourceManager.GetString("AppDbgExBkExtEdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to show the selected backup file in the file manager..
        /// </summary>
        internal static string AppDbgExBkFMan {
            get {
                return ResourceManager.GetString("AppDbgExBkFMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create the graphical settings backup of the selected game..
        /// </summary>
        internal static string AppDbgExBkSg {
            get {
                return ResourceManager.GetString("AppDbgExBkSg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to start the web browser to open the bug tracker URL..
        /// </summary>
        internal static string AppDbgExBugRep {
            get {
                return ResourceManager.GetString("AppDbgExBugRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while removing the FPS-config archive file..
        /// </summary>
        internal static string AppDbgExCfgArchRem {
            get {
                return ResourceManager.GetString("AppDbgExCfgArchRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create an automatic backup of the game configuration file before saving it in the Config Editor..
        /// </summary>
        internal static string AppDbgExCfgEdAutoBackup {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdAutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create a manual backup of the current config file..
        /// </summary>
        internal static string AppDbgExCfgEdBkMan {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdBkMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to copy an item to the clipboard in the Config Editor..
        /// </summary>
        internal static string AppDbgExCfgEdCopy {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to cut an item to the clipboard in the Config Editor..
        /// </summary>
        internal static string AppDbgExCfgEdCut {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to open the config file in the selected text editor..
        /// </summary>
        internal static string AppDbgExCfgEdExtEdt {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdExtEdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find and load the &quot;{0}&quot; FPS-config file by the Config Editor..
        /// </summary>
        internal static string AppDbgExCfgEditorLoad {
            get {
                return ResourceManager.GetString("AppDbgExCfgEditorLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while reading a config file in the Config Editor..
        /// </summary>
        internal static string AppDbgExCfgEdLoad {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to paste an item from the clipboard in the Config Editor..
        /// </summary>
        internal static string AppDbgExCfgEdPaste {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove an item in the Config Editor..
        /// </summary>
        internal static string AppDbgExCfgEdRemRow {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdRemRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during saving a file in the Config Editor..
        /// </summary>
        internal static string AppDbgExCfgEdSave {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during FPS config selection (click on warning icon)..
        /// </summary>
        internal static string AppDbgExCfgSelection {
            get {
                return ResourceManager.GetString("AppDbgExCfgSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the &quot;{0}&quot; file from the cleanup queue due to an error..
        /// </summary>
        internal static string AppDbgExClnDeleteFileFailure {
            get {
                return ResourceManager.GetString("AppDbgExClnDeleteFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while cleaning up empty directories..
        /// </summary>
        internal static string AppDbgExClnEmptyDirs {
            get {
                return ResourceManager.GetString("AppDbgExClnEmptyDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while building the list of files for cleanup..
        /// </summary>
        internal static string AppDbgExClnFindFilesFailure {
            get {
                return ResourceManager.GetString("AppDbgExClnFindFilesFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to show the selected file in the file manager..
        /// </summary>
        internal static string AppDbgExClnFm {
            get {
                return ResourceManager.GetString("AppDbgExClnFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown hotkey combination was pressed: Ctrl + {0}..
        /// </summary>
        internal static string AppDbgExClnHotkeyUnknown {
            get {
                return ResourceManager.GetString("AppDbgExClnHotkeyUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to find and remove the old application updates..
        /// </summary>
        internal static string AppDbgExClnOldUpdates {
            get {
                return ResourceManager.GetString("AppDbgExClnOldUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while cleaning up Steam package cache..
        /// </summary>
        internal static string AppDbgExClnPackages {
            get {
                return ResourceManager.GetString("AppDbgExClnPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while removing files from the queue..
        /// </summary>
        internal static string AppDbgExClnQueueRun {
            get {
                return ResourceManager.GetString("AppDbgExClnQueueRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while cleaning up Steam registry entries..
        /// </summary>
        internal static string AppDbgExClnReg {
            get {
                return ResourceManager.GetString("AppDbgExClnReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to configure the cryptographic policy..
        /// </summary>
        internal static string AppDbgExCryptoPolicy {
            get {
                return ResourceManager.GetString("AppDbgExCryptoPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while fetching Cvar description from a separate resource file..
        /// </summary>
        internal static string AppDbgExCvarDescFetchFailure {
            get {
                return ResourceManager.GetString("AppDbgExCvarDescFetchFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to detect the file system..
        /// </summary>
        internal static string AppDbgExDetectFileSystem {
            get {
                return ResourceManager.GetString("AppDbgExDetectFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to detect the installed games..
        /// </summary>
        internal static string AppDbgExDetectInstalledGames {
            get {
                return ResourceManager.GetString("AppDbgExDetectInstalledGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to report download progress to the form..
        /// </summary>
        internal static string AppDbgExDnProgressChanged {
            get {
                return ResourceManager.GetString("AppDbgExDnProgressChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while verifying the downloaded file &quot;{0}&quot;..
        /// </summary>
        internal static string AppDbgExDnResultVerify {
            get {
                return ResourceManager.GetString("AppDbgExDnResultVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while downloading the &quot;{0}&quot; file from the remote server to the local file &quot;{1}&quot;..
        /// </summary>
        internal static string AppDbgExDnWrkDownloadFile {
            get {
                return ResourceManager.GetString("AppDbgExDnWrkDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to start downloading file &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string AppDbgExDnWrkTask {
            get {
                return ResourceManager.GetString("AppDbgExDnWrkTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on trying to load the installed FPS-config into the Config Editor..
        /// </summary>
        internal static string AppDbgExEditCfg {
            get {
                return ResourceManager.GetString("AppDbgExEditCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while changing the selected FPS-config..
        /// </summary>
        internal static string AppDbgExFPSConfigSelectionChange {
            get {
                return ResourceManager.GetString("AppDbgExFPSConfigSelectionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during FPS config installation..
        /// </summary>
        internal static string AppDbgExFpsInstall {
            get {
                return ResourceManager.GetString("AppDbgExFpsInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while creating a backup file before installing a new FPS config..
        /// </summary>
        internal static string AppDbgExFpsInstBackup {
            get {
                return ResourceManager.GetString("AppDbgExFpsInstBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during FPS config uninstallation..
        /// </summary>
        internal static string AppDbgExFpsUninstall {
            get {
                return ResourceManager.GetString("AppDbgExFpsUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during saving video settings..
        /// </summary>
        internal static string AppDbgExGTSave {
            get {
                return ResourceManager.GetString("AppDbgExGTSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to build the list of available cleanup targets..
        /// </summary>
        internal static string AppDbgExHandleCleanupTargets {
            get {
                return ResourceManager.GetString("AppDbgExHandleCleanupTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to find and show installed FPS-configs..
        /// </summary>
        internal static string AppDbgExHandleConfigs {
            get {
                return ResourceManager.GetString("AppDbgExHandleConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to build the list of available FPS-configs..
        /// </summary>
        internal static string AppDbgExHandleFpsConfigs {
            get {
                return ResourceManager.GetString("AppDbgExHandleFpsConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to build the list of available game HUDs..
        /// </summary>
        internal static string AppDbgExHandleHUDs {
            get {
                return ResourceManager.GetString("AppDbgExHandleHUDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to fetch a HUD screenshot from the Internet..
        /// </summary>
        internal static string AppDbgExHandleHUDScreenshot {
            get {
                return ResourceManager.GetString("AppDbgExHandleHUDScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to get the current Steam User ID..
        /// </summary>
        internal static string AppDbgExHandleSteamIDs {
            get {
                return ResourceManager.GetString("AppDbgExHandleSteamIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the offline help viewer with the required page..
        /// </summary>
        internal static string AppDbgExHlpShow {
            get {
                return ResourceManager.GetString("AppDbgExHlpShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while removing the HUD archive file..
        /// </summary>
        internal static string AppDbgExHudArchRem {
            get {
                return ResourceManager.GetString("AppDbgExHudArchRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to show the selected HUD&apos;s directory in the file manager..
        /// </summary>
        internal static string AppDbgExHudExtFm {
            get {
                return ResourceManager.GetString("AppDbgExHudExtFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during HUD installation..
        /// </summary>
        internal static string AppDbgExHUDInstall {
            get {
                return ResourceManager.GetString("AppDbgExHUDInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove the temporary files after HUD installation..
        /// </summary>
        internal static string AppDbgExHUDInstallationCleanup {
            get {
                return ResourceManager.GetString("AppDbgExHUDInstallationCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to select another HUD..
        /// </summary>
        internal static string AppDbgExHudSelect {
            get {
                return ResourceManager.GetString("AppDbgExHudSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disable both WIN keys..
        /// </summary>
        internal static string AppDbgExKbBW {
            get {
                return ResourceManager.GetString("AppDbgExKbBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disable both WIN and CONTEXT keys..
        /// </summary>
        internal static string AppDbgExKbBWCtx {
            get {
                return ResourceManager.GetString("AppDbgExKbBWCtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disable left WIN key..
        /// </summary>
        internal static string AppDbgExKbLW {
            get {
                return ResourceManager.GetString("AppDbgExKbLW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disable all custom key overrides..
        /// </summary>
        internal static string AppDbgExKbRestore {
            get {
                return ResourceManager.GetString("AppDbgExKbRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disable right WIN and CONTEXT keys..
        /// </summary>
        internal static string AppDbgExKbRWCtx {
            get {
                return ResourceManager.GetString("AppDbgExKbRWCtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to run the external keyboard helper plugin..
        /// </summary>
        internal static string AppDbgExKbStart {
            get {
                return ResourceManager.GetString("AppDbgExKbStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while cleaning up the debug log file..
        /// </summary>
        internal static string AppDbgExLvClean {
            get {
                return ResourceManager.GetString("AppDbgExLvClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to load the active debug log file..
        /// </summary>
        internal static string AppDbgExLvLoad {
            get {
                return ResourceManager.GetString("AppDbgExLvLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create an automatic backup of the muted players file before saving it..
        /// </summary>
        internal static string AppDbgExMMAutoSave {
            get {
                return ResourceManager.GetString("AppDbgExMMAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to convert the selected items..
        /// </summary>
        internal static string AppDbgExMMConvertItems {
            get {
                return ResourceManager.GetString("AppDbgExMMConvertItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to copy the selected items to the clipboard..
        /// </summary>
        internal static string AppDbgExMMCopyItems {
            get {
                return ResourceManager.GetString("AppDbgExMMCopyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to cut the selected items to the clipboard..
        /// </summary>
        internal static string AppDbgExMMCutItems {
            get {
                return ResourceManager.GetString("AppDbgExMMCutItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception when trying to view the selected item&apos;s Steam profile in a web browser..
        /// </summary>
        internal static string AppDbgExMMOpenItemProfile {
            get {
                return ResourceManager.GetString("AppDbgExMMOpenItemProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to paste the items from the clipboard..
        /// </summary>
        internal static string AppDbgExMMPasteItems {
            get {
                return ResourceManager.GetString("AppDbgExMMPasteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while reading the muted users database..
        /// </summary>
        internal static string AppDbgExMMReadDb {
            get {
                return ResourceManager.GetString("AppDbgExMMReadDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to refresh the items from the database..
        /// </summary>
        internal static string AppDbgExMMRefresh {
            get {
                return ResourceManager.GetString("AppDbgExMMRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove the selected items..
        /// </summary>
        internal static string AppDbgExMMRemoveItems {
            get {
                return ResourceManager.GetString("AppDbgExMMRemoveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while writing to save the muted users database..
        /// </summary>
        internal static string AppDbgExMMSaveDb {
            get {
                return ResourceManager.GetString("AppDbgExMMSaveDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to register the available plugins..
        /// </summary>
        internal static string AppDbgExPluginRegister {
            get {
                return ResourceManager.GetString("AppDbgExPluginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create an instance of the PluginManager class..
        /// </summary>
        internal static string AppDbgExPluginsInit {
            get {
                return ResourceManager.GetString("AppDbgExPluginsInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to install the selected file..
        /// </summary>
        internal static string AppDbgExQIBaseInstall {
            get {
                return ResourceManager.GetString("AppDbgExQIBaseInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to generate a new configuration file from a template..
        /// </summary>
        internal static string AppDbgExQIGenerateConfig {
            get {
                return ResourceManager.GetString("AppDbgExQIGenerateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove the game settings..
        /// </summary>
        internal static string AppDbgExRemVd {
            get {
                return ResourceManager.GetString("AppDbgExRemVd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create an automatic backup of the game configs before removing them..
        /// </summary>
        internal static string AppDbgExRemVdAutoCfg {
            get {
                return ResourceManager.GetString("AppDbgExRemVdAutoCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the &quot;{0}&quot; file due to an error..
        /// </summary>
        internal static string AppDbgExRmFileFailure {
            get {
                return ResourceManager.GetString("AppDbgExRmFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while removing files..
        /// </summary>
        internal static string AppDbgExRmRf {
            get {
                return ResourceManager.GetString("AppDbgExRmRf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove a directory containing temporary files used during a report generation..
        /// </summary>
        internal static string AppDbgExRpCleanTempDir {
            get {
                return ResourceManager.GetString("AppDbgExRpCleanTempDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while generating the report..
        /// </summary>
        internal static string AppDbgExRpGenerate {
            get {
                return ResourceManager.GetString("AppDbgExRpGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mandatory report was not created..
        /// </summary>
        internal static string AppDbgExRpMdrNotCreated {
            get {
                return ResourceManager.GetString("AppDbgExRpMdrNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove a generated compressed report file..
        /// </summary>
        internal static string AppDbgExRpRemoveReportFile {
            get {
                return ResourceManager.GetString("AppDbgExRpRemoveReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to show the generated report file in a default file manager..
        /// </summary>
        internal static string AppDbgExRpShowReportFile {
            get {
                return ResourceManager.GetString("AppDbgExRpShowReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while switching the selected game by the user or the application itself..
        /// </summary>
        internal static string AppDbgExSelGame {
            get {
                return ResourceManager.GetString("AppDbgExSelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to shut down the running Steam client..
        /// </summary>
        internal static string AppDbgExShutdownClient {
            get {
                return ResourceManager.GetString("AppDbgExShutdownClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to start the cleanup..
        /// </summary>
        internal static string AppDbgExStartCleanup {
            get {
                return ResourceManager.GetString("AppDbgExStartCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to start the installed Steam client..
        /// </summary>
        internal static string AppDbgExStartClient {
            get {
                return ResourceManager.GetString("AppDbgExStartClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to get the Steam installation path. The program has been terminated..
        /// </summary>
        internal static string AppDbgExSteamPath {
            get {
                return ResourceManager.GetString("AppDbgExSteamPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Steam ID selection form due to insufficient SteamIDs in the list..
        /// </summary>
        internal static string AppDbgExStmIDsNotEnough {
            get {
                return ResourceManager.GetString("AppDbgExStmIDsNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while initializing the SteamManager class instance..
        /// </summary>
        internal static string AppDbgExStmmInit {
            get {
                return ResourceManager.GetString("AppDbgExStmmInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to run the Service automatic repair..
        /// </summary>
        internal static string AppDbgExSvcRepair {
            get {
                return ResourceManager.GetString("AppDbgExSvcRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to get the list of available backups..
        /// </summary>
        internal static string AppDbgExUpdateBackUpList {
            get {
                return ResourceManager.GetString("AppDbgExUpdateBackUpList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to install the binary update..
        /// </summary>
        internal static string AppDbgExUpdBinInst {
            get {
                return ResourceManager.GetString("AppDbgExUpdBinInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while checking for updates during the Updates form initialization..
        /// </summary>
        internal static string AppDbgExUpdChk {
            get {
                return ResourceManager.GetString("AppDbgExUpdChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to start the web browser to open the cvarlist URL..
        /// </summary>
        internal static string AppDbgExUrlCvList {
            get {
                return ResourceManager.GetString("AppDbgExUrlCvList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to start the web browser to open the Steam group profile..
        /// </summary>
        internal static string AppDbgExUrlGroup {
            get {
                return ResourceManager.GetString("AppDbgExUrlGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to start the web browser to open the HUD&apos;s homepage..
        /// </summary>
        internal static string AppDbgExUrlHudHome {
            get {
                return ResourceManager.GetString("AppDbgExUrlHudHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to start the web browser to open the Steam profile..
        /// </summary>
        internal static string AppDbgExUrlStmSel {
            get {
                return ResourceManager.GetString("AppDbgExUrlStmSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to start the web browser to open the official website..
        /// </summary>
        internal static string AppDbgExUrlWebsite {
            get {
                return ResourceManager.GetString("AppDbgExUrlWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during a new SteamID selection..
        /// </summary>
        internal static string AppDbgExUserIdSel {
            get {
                return ResourceManager.GetString("AppDbgExUserIdSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to launch Steam to validate the game cache..
        /// </summary>
        internal static string AppDbgExValCache {
            get {
                return ResourceManager.GetString("AppDbgExValCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create a backup of the game video settings..
        /// </summary>
        internal static string AppDbgExVideoBackUpFail {
            get {
                return ResourceManager.GetString("AppDbgExVideoBackUpFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while loading the game video settings..
        /// </summary>
        internal static string AppDbgExVideoLoadFail {
            get {
                return ResourceManager.GetString("AppDbgExVideoLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove the game video settings..
        /// </summary>
        internal static string AppDbgExVideoRemoveFail {
            get {
                return ResourceManager.GetString("AppDbgExVideoRemoveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while parsing the XML game database. The program has been terminated..
        /// </summary>
        internal static string AppDbgExXmlParse {
            get {
                return ResourceManager.GetString("AppDbgExXmlParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download FPS-config from the main server. Trying mirror..
        /// </summary>
        internal static string AppDbgFPSDnlMain {
            get {
                return ResourceManager.GetString("AppDbgFPSDnlMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download FPS-config from the secondary server. All mirrors were tried..
        /// </summary>
        internal static string AppDbgFPSDnlMirror {
            get {
                return ResourceManager.GetString("AppDbgFPSDnlMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download HUD archive from the main server. Trying mirror..
        /// </summary>
        internal static string AppDbgHUDDnlMain {
            get {
                return ResourceManager.GetString("AppDbgHUDDnlMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download HUD archive from the secondary server. All mirrors were tried..
        /// </summary>
        internal static string AppDbgHUDDnlMirror {
            get {
                return ResourceManager.GetString("AppDbgHUDDnlMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect or unsupported SourceType specified..
        /// </summary>
        internal static string AppDbgIncorrectSourceType {
            get {
                return ResourceManager.GetString("AppDbgIncorrectSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &quot;{0}&quot; failed to validate and was ignored..
        /// </summary>
        internal static string AppDbgMutedPlayersWrongFormat {
            get {
                return ResourceManager.GetString("AppDbgMutedPlayersWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown file type has been selected. The installation is not possible..
        /// </summary>
        internal static string AppDbgQIUnknownFileType {
            get {
                return ResourceManager.GetString("AppDbgQIUnknownFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform elevation. The user closed the UAC dialog..
        /// </summary>
        internal static string AppDbgUACCancel {
            get {
                return ResourceManager.GetString("AppDbgUACCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unpack because the archive file was not found..
        /// </summary>
        internal static string AppDbgZipExtractArchiveNotFound {
            get {
                return ResourceManager.GetString("AppDbgZipExtractArchiveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unpack the &quot;{0}&quot; file from the Zip archive due to an error..
        /// </summary>
        internal static string AppDbgZipExtractFailure {
            get {
                return ResourceManager.GetString("AppDbgZipExtractFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive tries to traverse through the base archive directory!.
        /// </summary>
        internal static string AppDbgZipPathTraversalDetected {
            get {
                return ResourceManager.GetString("AppDbgZipPathTraversalDetected", resourceCulture);
            }
        }
    }
}
