#
# SPDX-FileCopyrightText: 2011-2022 EasyCoding Team
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

name: Question
description: Ask a question about the project
labels: [question]
body:
  - type: textarea
    attributes:
      label: Question
      placeholder: Ask a question about the project here.
    validations:
      required: true
