//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srcrepair.gui.kbhelper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("srcrepair.gui.kbhelper.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is already running. Starting the second copy is not allowed..
        /// </summary>
        internal static string KB_AlrLaunched {
            get {
                return ResourceManager.GetString("KB_AlrLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to {0}?.
        /// </summary>
        internal static string KB_DisableQuestion {
            get {
                return ResourceManager.GetString("KB_DisableQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to disable both WIN buttons!.
        /// </summary>
        internal static string KB_ExBothWin {
            get {
                return ResourceManager.GetString("KB_ExBothWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to both WIN and MENU buttons!.
        /// </summary>
        internal static string KB_ExBothWinMenu {
            get {
                return ResourceManager.GetString("KB_ExBothWinMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to disable left WIN button!.
        /// </summary>
        internal static string KB_ExLeftWin {
            get {
                return ResourceManager.GetString("KB_ExLeftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to restore default settings!.
        /// </summary>
        internal static string KB_ExRestore {
            get {
                return ResourceManager.GetString("KB_ExRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to right WIN and MENU buttons!.
        /// </summary>
        internal static string KB_ExRWinMenu {
            get {
                return ResourceManager.GetString("KB_ExRWinMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program must be run with admin rights!.
        /// </summary>
        internal static string KB_NoAdminRights {
            get {
                return ResourceManager.GetString("KB_NoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but this operating system is not supported by this application!.
        /// </summary>
        internal static string KB_OSNotSupported {
            get {
                return ResourceManager.GetString("KB_OSNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default settings?.
        /// </summary>
        internal static string KB_RestoreQuestion {
            get {
                return ResourceManager.GetString("KB_RestoreQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required action has been successfully completed!.
        /// </summary>
        internal static string KB_Success {
            get {
                return ResourceManager.GetString("KB_Success", resourceCulture);
            }
        }
    }
}
