//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srcrepair.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("srcrepair.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string AppOpenHandlerEscapeTemplate {
            get {
                return ResourceManager.GetString("AppOpenHandlerEscapeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xdg-open.
        /// </summary>
        internal static string AppOpenHandlerLin {
            get {
                return ResourceManager.GetString("AppOpenHandlerLin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        internal static string AppOpenHandlerMac {
            get {
                return ResourceManager.GetString("AppOpenHandlerMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (mono).
        /// </summary>
        internal static string AppUserAgentSuffixOther {
            get {
                return ResourceManager.GetString("AppUserAgentSuffixOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT.
        /// </summary>
        internal static string AppUserAgentSuffixWin {
            get {
                return ResourceManager.GetString("AppUserAgentSuffixWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 ({0} {1} {2}; {3}; {4}) {5}/{6}).
        /// </summary>
        internal static string AppUserAgentTemplate {
            get {
                return ResourceManager.GetString("AppUserAgentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backups.
        /// </summary>
        internal static string BackUpLocalDir {
            get {
                return ResourceManager.GetString("BackUpLocalDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configs.xml.
        /// </summary>
        internal static string CfgDbFile {
            get {
                return ResourceManager.GetString("CfgDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cfgs.
        /// </summary>
        internal static string CfgLocalDir {
            get {
                return ResourceManager.GetString("CfgLocalDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cleanup.xml.
        /// </summary>
        internal static string CleanupDbFile {
            get {
                return ResourceManager.GetString("CleanupDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games.xml.
        /// </summary>
        internal static string GameListFile {
            get {
                return ResourceManager.GetString("GameListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to huds.xml.
        /// </summary>
        internal static string HUDDbFile {
            get {
                return ResourceManager.GetString("HUDDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUDs.
        /// </summary>
        internal static string HUDLocalDir {
            get {
                return ResourceManager.GetString("HUDLocalDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logs.
        /// </summary>
        internal static string LogLocalDir {
            get {
                return ResourceManager.GetString("LogLocalDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debug.log.
        /// </summary>
        internal static string LogMainFile {
            get {
                return ResourceManager.GetString("LogMainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[0-9a-zA-Z :()-_./\\\\]*$.
        /// </summary>
        internal static string PathValidateRegex {
            get {
                return ResourceManager.GetString("PathValidateRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins.xml.
        /// </summary>
        internal static string PluginsDbFile {
            get {
                return ResourceManager.GetString("PluginsDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portable.
        /// </summary>
        internal static string PortableLocalDir {
            get {
                return ResourceManager.GetString("PortableLocalDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reg.exe.
        /// </summary>
        internal static string RegExecutable {
            get {
                return ResourceManager.GetString("RegExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export &quot;{0}&quot; &quot;{1}&quot; /y.
        /// </summary>
        internal static string RegExportCmdLine {
            get {
                return ResourceManager.GetString("RegExportCmdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import &quot;{0}&quot;.
        /// </summary>
        internal static string RegImportCmdLine {
            get {
                return ResourceManager.GetString("RegImportCmdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_{1}.reg.
        /// </summary>
        internal static string RegOutFilePattern {
            get {
                return ResourceManager.GetString("RegOutFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reports.
        /// </summary>
        internal static string ReportLocalDir {
            get {
                return ResourceManager.GetString("ReportLocalDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explorer.exe.
        /// </summary>
        internal static string ShBinWin {
            get {
                return ResourceManager.GetString("ShBinWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /select,.
        /// </summary>
        internal static string ShParamWin {
            get {
                return ResourceManager.GetString("ShParamWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steamapps.
        /// </summary>
        internal static string SteamAppsFolderNameLin {
            get {
                return ResourceManager.GetString("SteamAppsFolderNameLin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steamapps.
        /// </summary>
        internal static string SteamAppsFolderNameMac {
            get {
                return ResourceManager.GetString("SteamAppsFolderNameMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamApps.
        /// </summary>
        internal static string SteamAppsFolderNameWin {
            get {
                return ResourceManager.GetString("SteamAppsFolderNameWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam.
        /// </summary>
        internal static string SteamExecBinLin {
            get {
                return ResourceManager.GetString("SteamExecBinLin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam.
        /// </summary>
        internal static string SteamExecBinMac {
            get {
                return ResourceManager.GetString("SteamExecBinMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.exe.
        /// </summary>
        internal static string SteamExecBinWin {
            get {
                return ResourceManager.GetString("SteamExecBinWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        internal static string SteamFolderNameLin {
            get {
                return ResourceManager.GetString("SteamFolderNameLin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        internal static string SteamFolderNameMac {
            get {
                return ResourceManager.GetString("SteamFolderNameMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        internal static string SteamFolderNameWin {
            get {
                return ResourceManager.GetString("SteamFolderNameWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam.
        /// </summary>
        internal static string SteamProcNameLin {
            get {
                return ResourceManager.GetString("SteamProcNameLin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam.
        /// </summary>
        internal static string SteamProcNameMac {
            get {
                return ResourceManager.GetString("SteamProcNameMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        internal static string SteamProcNameWin {
            get {
                return ResourceManager.GetString("SteamProcNameWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.easycoding.org/files/srcrepair/updates/updates.xml.
        /// </summary>
        internal static string UpdateDBURL {
            get {
                return ResourceManager.GetString("UpdateDBURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updates.
        /// </summary>
        internal static string UpdateLocalDir {
            get {
                return ResourceManager.GetString("UpdateLocalDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d{2,12}.
        /// </summary>
        internal static string UserIDParseRegex {
            get {
                return ResourceManager.GetString("UserIDParseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d{2,12}$.
        /// </summary>
        internal static string UserIDValidateRegex {
            get {
                return ResourceManager.GetString("UserIDValidateRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.{2}.
        /// </summary>
        internal static string VersionNumberString {
            get {
                return ResourceManager.GetString("VersionNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoAutoCfg.
        /// </summary>
        internal static string VideoFileAutoPrefix {
            get {
                return ResourceManager.GetString("VideoFileAutoPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoCfg.
        /// </summary>
        internal static string VideoFileManualPrefix {
            get {
                return ResourceManager.GetString("VideoFileManualPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game_AutoBackUp.
        /// </summary>
        internal static string VideoRegAutoPrefix {
            get {
                return ResourceManager.GetString("VideoRegAutoPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game_Options.
        /// </summary>
        internal static string VideoRegManualPrefix {
            get {
                return ResourceManager.GetString("VideoRegManualPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workshop.
        /// </summary>
        internal static string WorkshopFolderName {
            get {
                return ResourceManager.GetString("WorkshopFolderName", resourceCulture);
            }
        }
    }
}
