//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srcrepair {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("srcrepair.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items selected. Please select and then try again!.
        /// </summary>
        internal static string AC_NoItemsSelected {
            get {
                return ResourceManager.GetString("AC_NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Parse error detected. Probably file {0} is opened not completely or with errors..
        /// </summary>
        internal static string AHE_ExceptionDetected {
            get {
                return ResourceManager.GetString("AHE_ExceptionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts file: {0}. Show it in Windows Explorer?.
        /// </summary>
        internal static string AHE_HMessg {
            get {
                return ResourceManager.GetString("AHE_HMessg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get path to the Hosts file from registry. Will try standard path..
        /// </summary>
        internal static string AHE_KRegErr {
            get {
                return ResourceManager.GetString("AHE_KRegErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local admin rights is required to perform requested action!.
        /// </summary>
        internal static string AHE_NoAdminRights {
            get {
                return ResourceManager.GetString("AHE_NoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hosts file on the resulting path {0} could not be found..
        /// </summary>
        internal static string AHE_NoFileDetected {
            get {
                return ResourceManager.GetString("AHE_NoFileDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default Hosts file?.
        /// </summary>
        internal static string AHE_RestDef {
            get {
                return ResourceManager.GetString("AHE_RestDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File hosts was successfully saved!.
        /// </summary>
        internal static string AHE_Saved {
            get {
                return ResourceManager.GetString("AHE_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! An error occurred while writing to file {0}. Maybe you have not enough rights for this or someone is blocking write attempts..
        /// </summary>
        internal static string AHE_SaveException {
            get {
                return ResourceManager.GetString("AHE_SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already running. Starting the second copy is not allowed!.
        /// </summary>
        internal static string AppAlreadyLaunched {
            get {
                return ResourceManager.GetString("AppAlreadyLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! On the selected Steam login we can&apos;t detect any installed supported games. Please select another login from list..
        /// </summary>
        internal static string AppChangeLogin {
            get {
                return ResourceManager.GetString("AppChangeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for Updates... Please wait..
        /// </summary>
        internal static string AppCheckingForUpdates {
            get {
                return ResourceManager.GetString("AppCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://developer.valvesoftware.com/wiki/Console_Command_List.
        /// </summary>
        internal static string AppCVListURL {
            get {
                return ResourceManager.GetString("AppCVListURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug log has been disabled. Please enable it first in application settings..
        /// </summary>
        internal static string AppDebugDisabled {
            get {
                return ResourceManager.GetString("AppDebugDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string AppDefaultSteamLangID {
            get {
                return ResourceManager.GetString("AppDefaultSteamLangID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Failed to get data from game database. Please try again or select another game!.
        /// </summary>
        internal static string AppFailedToGetData {
            get {
                return ResourceManager.GetString("AppFailedToGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the selected feature is not available for this platform!.
        /// </summary>
        internal static string AppFeatureUnavailable {
            get {
                return ResourceManager.GetString("AppFeatureUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game work directory &quot;{0}&quot; does not exists!.
        /// </summary>
        internal static string AppGameChkErrNtExs {
            get {
                return ResourceManager.GetString("AppGameChkErrNtExs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error occurred! The application will be terminated..
        /// </summary>
        internal static string AppGenericError {
            get {
                return ResourceManager.GetString("AppGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string AppLangPrefix {
            get {
                return ResourceManager.GetString("AppLangPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with graphical settings was not found. Please run the game at least once..
        /// </summary>
        internal static string AppNCFCFGNotExists {
            get {
                return ResourceManager.GetString("AppNCFCFGNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug log file not found!.
        /// </summary>
        internal static string AppNoDebugFile {
            get {
                return ResourceManager.GetString("AppNoDebugFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! SRC Repair can&apos;t detect any installed supported games. Please run your desired game from Steam at least once. After that, they will appear in the list and you will be able to manage them by this program..
        /// </summary>
        internal static string AppNoGamesDetected {
            get {
                return ResourceManager.GetString("AppNoGamesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No games detected. Steam located as: {0}..
        /// </summary>
        internal static string AppNoGamesDLog {
            get {
                return ResourceManager.GetString("AppNoGamesDLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! No games selected. Select game and try again later..
        /// </summary>
        internal static string AppNoGamesSelected {
            get {
                return ResourceManager.GetString("AppNoGamesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error! Can&apos;t read directory SteamApps. Maybe it does not exists or you do not have necessary rights. Further program execution is impossible. Install and run at least one game from Steam and then use this program again..
        /// </summary>
        internal static string AppNoSTADetected {
            get {
                return ResourceManager.GetString("AppNoSTADetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonASCII characters detected. Path: {0}..
        /// </summary>
        internal static string AppRestrSymbLog {
            get {
                return ResourceManager.GetString("AppRestrSymbLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! You have disabled SafeClean module, so backups will not be created until its re-activation..
        /// </summary>
        internal static string AppSafeClnDisabled {
            get {
                return ResourceManager.GetString("AppSafeClnDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackUps: OFF.
        /// </summary>
        internal static string AppSafeClnStTextOff {
            get {
                return ResourceManager.GetString("AppSafeClnStTextOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackUps: ON.
        /// </summary>
        internal static string AppSafeClnStTextOn {
            get {
                return ResourceManager.GetString("AppSafeClnStTextOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string AppSizeBytes {
            get {
                return ResourceManager.GetString("AppSizeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string AppSizeGigabytes {
            get {
                return ResourceManager.GetString("AppSizeGigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string AppSizeKilobytes {
            get {
                return ResourceManager.GetString("AppSizeKilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string AppSizeMegabytes {
            get {
                return ResourceManager.GetString("AppSizeMegabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start Steam. Please reinstall and try again later..
        /// </summary>
        internal static string AppStartSteamFailed {
            get {
                return ResourceManager.GetString("AppStartSteamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam found in: {0}..
        /// </summary>
        internal static string AppSteamLocLog {
            get {
                return ResourceManager.GetString("AppSteamLocLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice! Update for {0} is available. We recommend you upgrade as soon as possible via the menu Help - Check for updates, or manually..
        /// </summary>
        internal static string AppUpdateAvailable {
            get {
                return ResourceManager.GetString("AppUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing XML file with a list of games. Perhaps it is missing or damaged. Please reinstall the program..
        /// </summary>
        internal static string AppXMLParseError {
            get {
                return ResourceManager.GetString("AppXMLParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during unpacking selected archive. Additional information can be found in debug log..
        /// </summary>
        internal static string AR_UnpackException {
            get {
                return ResourceManager.GetString("AR_UnpackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the backup. Backup has been created!.
        /// </summary>
        internal static string BackUpCreationFailed {
            get {
                return ResourceManager.GetString("BackUpCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect CAPTCHA code entered. Try again!.
        /// </summary>
        internal static string BR_CaptErr {
            get {
                return ResourceManager.GetString("BR_CaptErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty fields detected. Fill them and try again!.
        /// </summary>
        internal static string BR_MsgFieldsEmpty {
            get {
                return ResourceManager.GetString("BR_MsgFieldsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        internal static string BR_SendButtonAlt {
            get {
                return ResourceManager.GetString("BR_SendButtonAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug report has been successfully sended!.
        /// </summary>
        internal static string BR_SendCompleted {
            get {
                return ResourceManager.GetString("BR_SendCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! An error occured. Please try again later!.
        /// </summary>
        internal static string BR_SendError {
            get {
                return ResourceManager.GetString("BR_SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is a binary. Unable open it in text editor!.
        /// </summary>
        internal static string BU_BinaryFile {
            get {
                return ResourceManager.GetString("BU_BinaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive of.
        /// </summary>
        internal static string BU_BName_Bud {
            get {
                return ResourceManager.GetString("BU_BName_Bud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game config of.
        /// </summary>
        internal static string BU_BName_Config {
            get {
                return ResourceManager.GetString("BU_BName_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph. options autobackup of.
        /// </summary>
        internal static string BU_BName_GameAuto {
            get {
                return ResourceManager.GetString("BU_BName_GameAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph. settings of.
        /// </summary>
        internal static string BU_BName_GRGame {
            get {
                return ResourceManager.GetString("BU_BName_GRGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All SRC graph. settings of.
        /// </summary>
        internal static string BU_BName_SRCAll {
            get {
                return ResourceManager.GetString("BU_BName_SRCAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam options of.
        /// </summary>
        internal static string BU_BName_SteamAll {
            get {
                return ResourceManager.GetString("BU_BName_SteamAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted players.
        /// </summary>
        internal static string BU_BName_VChat {
            get {
                return ResourceManager.GetString("BU_BName_VChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string BU_BType_Cfg {
            get {
                return ResourceManager.GetString("BU_BType_Cfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string BU_BType_Cont {
            get {
                return ResourceManager.GetString("BU_BType_Cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string BU_BType_DB {
            get {
                return ResourceManager.GetString("BU_BType_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        internal static string BU_BType_Reg {
            get {
                return ResourceManager.GetString("BU_BType_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string BU_BType_Unkn {
            get {
                return ResourceManager.GetString("BU_BType_Unkn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string BU_BType_Video {
            get {
                return ResourceManager.GetString("BU_BType_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file can not be restored directly from SRC Repair. Open it with any archiver and restore files manually..
        /// </summary>
        internal static string BU_BudArchiveMsg {
            get {
                return ResourceManager.GetString("BU_BudArchiveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error occured. File was not removed!.
        /// </summary>
        internal static string BU_DelFailed {
            get {
                return ResourceManager.GetString("BU_DelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected backup file?.
        /// </summary>
        internal static string BU_DelMsg {
            get {
                return ResourceManager.GetString("BU_DelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup was successfully removed!.
        /// </summary>
        internal static string BU_DelSuccessful {
            get {
                return ResourceManager.GetString("BU_DelSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error occured. Can&apos;t get list of backups. Create at least one backup and try again later..
        /// </summary>
        internal static string BU_ListLdFailed {
            get {
                return ResourceManager.GetString("BU_ListLdFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup files detected. Please, refresh list and try again later!.
        /// </summary>
        internal static string BU_NoFiles {
            get {
                return ResourceManager.GetString("BU_NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is impossible: no files selected!.
        /// </summary>
        internal static string BU_NoSelected {
            get {
                return ResourceManager.GetString("BU_NoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore file {0} of {1}?.
        /// </summary>
        internal static string BU_QMsg {
            get {
                return ResourceManager.GetString("BU_QMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create registry backup now?.
        /// </summary>
        internal static string BU_RegCreate {
            get {
                return ResourceManager.GetString("BU_RegCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry backup was successfully created!.
        /// </summary>
        internal static string BU_RegDone {
            get {
                return ResourceManager.GetString("BU_RegDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error occured. Backup file was not created!.
        /// </summary>
        internal static string BU_RegErr {
            get {
                return ResourceManager.GetString("BU_RegErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error occured. BackUp was not restored!.
        /// </summary>
        internal static string BU_RestFailed {
            get {
                return ResourceManager.GetString("BU_RestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackUp was successfully restored!.
        /// </summary>
        internal static string BU_RestSuccessful {
            get {
                return ResourceManager.GetString("BU_RestSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select item from drop-down list!.
        /// </summary>
        internal static string BU_TBSelCat {
            get {
                return ResourceManager.GetString("BU_TBSelCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file type. Can&apos;t restore!.
        /// </summary>
        internal static string BU_UnknownType {
            get {
                return ResourceManager.GetString("BU_UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup of {0} was successfully created!.
        /// </summary>
        internal static string CE_BackUpCreated {
            get {
                return ResourceManager.GetString("CE_BackUpCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the configuration file?.
        /// </summary>
        internal static string CE_CfgSV {
            get {
                return ResourceManager.GetString("CE_CfgSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! When saving a file error occurred. File was not saved!.
        /// </summary>
        internal static string CE_CfgSVVEx {
            get {
                return ResourceManager.GetString("CE_CfgSVVEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately we have no description for this variable. You can help by sending it to us..
        /// </summary>
        internal static string CE_ClNoDescr {
            get {
                return ResourceManager.GetString("CE_ClNoDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No variables detected in selected row!.
        /// </summary>
        internal static string CE_ClSelErr {
            get {
                return ResourceManager.GetString("CE_ClSelErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a backup file.
        /// </summary>
        internal static string CE_CreateBackUp {
            get {
                return ResourceManager.GetString("CE_CreateBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Parse error detected. Probably the config is opened not completely or with errors..
        /// </summary>
        internal static string CE_ExceptionDetected {
            get {
                return ResourceManager.GetString("CE_ExceptionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file to use this feature..
        /// </summary>
        internal static string CE_NoFileOpened {
            get {
                return ResourceManager.GetString("CE_NoFileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read the contents of the config, as file not found!.
        /// </summary>
        internal static string CE_OpenFailed {
            get {
                return ResourceManager.GetString("CE_OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! It is not recommended to edit this file, because this may lead to unpredictable consequences. Edit it at your own risk..
        /// </summary>
        internal static string CE_RestConfigOpenWarn {
            get {
                return ResourceManager.GetString("CE_RestConfigOpenWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates. Please wait!.
        /// </summary>
        internal static string DB_WrkInProgress {
            get {
                return ResourceManager.GetString("DB_WrkInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error: can not install the selected config!.
        /// </summary>
        internal static string FP_InstallFailed {
            get {
                return ResourceManager.GetString("FP_InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Setting FPS-config reduce all graphics settings to the absolute minimum that will lead to significant deterioration of the quality of game graphics and game performance increase. Are you sure you want to set the FPS-config?.
        /// </summary>
        internal static string FP_InstallQuestion {
            get {
                return ResourceManager.GetString("FP_InstallQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config has been successfully installed!.
        /// </summary>
        internal static string FP_InstallSuccessful {
            get {
                return ResourceManager.GetString("FP_InstallSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! For the selected game we do not have FPS-config, so this page will be disabled!.
        /// </summary>
        internal static string FP_NoCfgGame {
            get {
                return ResourceManager.GetString("FP_NoCfgGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, the description of the chosen config is not available. We apologize for any inconvenience..
        /// </summary>
        internal static string FP_NoDescr {
            get {
                return ResourceManager.GetString("FP_NoDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали FPS-конфиг из списка. Выберите конфиг и повторите попытку!.
        /// </summary>
        internal static string FP_NothingSelected {
            get {
                return ResourceManager.GetString("FP_NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing the installed config!.
        /// </summary>
        internal static string FP_RemoveFailed {
            get {
                return ResourceManager.GetString("FP_RemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needless to delete: FPS-config for the current game is not installed!.
        /// </summary>
        internal static string FP_RemoveNotExists {
            get {
                return ResourceManager.GetString("FP_RemoveNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete installed config?.
        /// </summary>
        internal static string FP_RemoveQuestion {
            get {
                return ResourceManager.GetString("FP_RemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed FPS-config has been successfully deleted!.
        /// </summary>
        internal static string FP_RemoveSuccessful {
            get {
                return ResourceManager.GetString("FP_RemoveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the config file from the list above!.
        /// </summary>
        internal static string FP_SelectFromList {
            get {
                return ResourceManager.GetString("FP_SelectFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your own FPS-config was successfully generated and loaded to Config Editor. You can now edit it manually. Please save it as autoexec.cfg to apply in game..
        /// </summary>
        internal static string FPW_Success {
            get {
                return ResourceManager.GetString("FPW_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close {0}?.
        /// </summary>
        internal static string FrmCloseQuery {
            get {
                return ResourceManager.GetString("FrmCloseQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Restricted symbols detected in selected games&apos; path. Steam and the games will not work correctly..
        /// </summary>
        internal static string GameNonASCIIDetected {
            get {
                return ResourceManager.GetString("GameNonASCIIDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game installed correctly: directory path does not contain illegal characters..
        /// </summary>
        internal static string GameNonASCIINotDetected {
            get {
                return ResourceManager.GetString("GameNonASCIINotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an unhandled exception. Please inform the developers email: vitaly@easycoding.org..
        /// </summary>
        internal static string GeneralErrorDetected {
            get {
                return ResourceManager.GetString("GeneralErrorDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable DirectX 8 mode rendering? This will significantly increase the performance of the game..
        /// </summary>
        internal static string GT_DxLevelMsg {
            get {
                return ResourceManager.GetString("GT_DxLevelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! An installed FPS-config detected, so the settings from this page except the DirectX mode will be ignored by the game until you remove this config..
        /// </summary>
        internal static string GT_FPSCfgDetected {
            get {
                return ResourceManager.GetString("GT_FPSCfgDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to set the graphics settings to the recommended maximum? This will require a powerful computer!.
        /// </summary>
        internal static string GT_MaxPerfMsg {
            get {
                return ResourceManager.GetString("GT_MaxPerfMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to install all the video settings to minimum? This will increase the FPS, but worsen the graphics in the game..
        /// </summary>
        internal static string GT_MinPerfMsg {
            get {
                return ResourceManager.GetString("GT_MinPerfMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the game graphics settings into a file!.
        /// </summary>
        internal static string GT_NCFFailure {
            get {
                return ResourceManager.GetString("GT_NCFFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! To save the graphical settings, you must fill in all the forms!.
        /// </summary>
        internal static string GT_NCFNReady {
            get {
                return ResourceManager.GetString("GT_NCFNReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. Do not forget to adjust and save the changes in the settings!.
        /// </summary>
        internal static string GT_PerfSet {
            get {
                return ResourceManager.GetString("GT_PerfSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open registry key. Please start game at least once and try again..
        /// </summary>
        internal static string GT_RegOpenErr {
            get {
                return ResourceManager.GetString("GT_RegOpenErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the {0} resolution of the monitor or window. You must specify an integer..
        /// </summary>
        internal static string GT_ResMsg {
            get {
                return ResourceManager.GetString("GT_ResMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horisontal.
        /// </summary>
        internal static string GT_ResMsgHor {
            get {
                return ResourceManager.GetString("GT_ResMsgHor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical.
        /// </summary>
        internal static string GT_ResMsgVert {
            get {
                return ResourceManager.GetString("GT_ResMsgVert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving graphical settings!.
        /// </summary>
        internal static string GT_SaveFailure {
            get {
                return ResourceManager.GetString("GT_SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your changes?.
        /// </summary>
        internal static string GT_SaveMsg {
            get {
                return ResourceManager.GetString("GT_SaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have been successfully saved!.
        /// </summary>
        internal static string GT_SaveSuccess {
            get {
                return ResourceManager.GetString("GT_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected HUD already installed. If you want to reinstall, remove it first!.
        /// </summary>
        internal static string HD_AlreadyInstalled {
            get {
                return ResourceManager.GetString("HD_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install selected HUD.
        /// </summary>
        internal static string HD_BtnInstallText {
            get {
                return ResourceManager.GetString("HD_BtnInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update selected HUD.
        /// </summary>
        internal static string HD_BtnUpdateText {
            get {
                return ResourceManager.GetString("HD_BtnUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD database outdated. Please update database from menu Help..
        /// </summary>
        internal static string HD_DbOutdated {
            get {
                return ResourceManager.GetString("HD_DbOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD database {0}. Last update: {1}..
        /// </summary>
        internal static string HD_DynBarText {
            get {
                return ResourceManager.GetString("HD_DynBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing HUD... Wait..
        /// </summary>
        internal static string HD_InstallBtnProgress {
            get {
                return ResourceManager.GetString("HD_InstallBtnProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during installation. Please try again later..
        /// </summary>
        internal static string HD_InstallError {
            get {
                return ResourceManager.GetString("HD_InstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD installation successfull!.
        /// </summary>
        internal static string HD_InstallSuccessfull {
            get {
                return ResourceManager.GetString("HD_InstallSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected HUD is not fully compatible with the latest version of the game. We recommend you to upgrade the HUD database..
        /// </summary>
        internal static string HD_NotTested {
            get {
                return ResourceManager.GetString("HD_NotTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of outdated HUDs not allowed. Please update database or select another HUD..
        /// </summary>
        internal static string HD_Outdated {
            get {
                return ResourceManager.GetString("HD_Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outdated.
        /// </summary>
        internal static string HD_StatusOutdated {
            get {
                return ResourceManager.GetString("HD_StatusOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actual.
        /// </summary>
        internal static string HD_StatusUpdated {
            get {
                return ResourceManager.GetString("HD_StatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string InputBoxCancelBtnName {
            get {
                return ResourceManager.GetString("InputBoxCancelBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during execution. Make sure you have administrator rights!.
        /// </summary>
        internal static string KB_ExException {
            get {
                return ResourceManager.GetString("KB_ExException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to {0}?.
        /// </summary>
        internal static string KB_ExQuestion {
            get {
                return ResourceManager.GetString("KB_ExQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default settings?.
        /// </summary>
        internal static string KB_ExRestore {
            get {
                return ResourceManager.GetString("KB_ExRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required action successfully completed!.
        /// </summary>
        internal static string KB_ExSuccess {
            get {
                return ResourceManager.GetString("KB_ExSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not purge log file! Please try again later..
        /// </summary>
        internal static string LV_ClearEx {
            get {
                return ResourceManager.GetString("LV_ClearEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load error log. Try again later..
        /// </summary>
        internal static string LV_LoadFailed {
            get {
                return ResourceManager.GetString("LV_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by {1}..
        /// </summary>
        internal static string MM_AboutDlg {
            get {
                return ResourceManager.GetString("MM_AboutDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error detected while parsing game banlist file. Try again later..
        /// </summary>
        internal static string MM_ExceptionDetected {
            get {
                return ResourceManager.GetString("MM_ExceptionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated!.
        /// </summary>
        internal static string MM_SavedOK {
            get {
                return ResourceManager.GetString("MM_SavedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error detected while saving database to file. File may be damaged..
        /// </summary>
        internal static string MM_SaveException {
            get {
                return ResourceManager.GetString("MM_SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but this feature is not yet implemented!.
        /// </summary>
        internal static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! An error occurred while saving!.
        /// </summary>
        internal static string Opts_Error {
            get {
                return ResourceManager.GetString("Opts_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings were saved successfully. Attention! Some of them will be activated only after restarting the program..
        /// </summary>
        internal static string Opts_Saved {
            get {
                return ResourceManager.GetString("Opts_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered the command line parameter, but not found its value, so ignore this option!.
        /// </summary>
        internal static string ParamError {
            get {
                return ResourceManager.GetString("ParamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} application is running! To execute this cleanup please close it..
        /// </summary>
        internal static string PS_AppRunning {
            get {
                return ResourceManager.GetString("PS_AppRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! An error occured during packing files. Archive was not created!.
        /// </summary>
        internal static string PS_ArchFailed {
            get {
                return ResourceManager.GetString("PS_ArchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup successfully completed! You should run game cache integrity check now..
        /// </summary>
        internal static string PS_CacheChkReq {
            get {
                return ResourceManager.GetString("PS_CacheChkReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the clean up empty directories! Maybe you do not have appropriate access rights..
        /// </summary>
        internal static string PS_CleanEmptyDirsError {
            get {
                return ResourceManager.GetString("PS_CleanEmptyDirsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during cleanup. Perhaps you have no rights necessary for this action..
        /// </summary>
        internal static string PS_CleanException {
            get {
                return ResourceManager.GetString("PS_CleanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up....
        /// </summary>
        internal static string PS_CleanInProgress {
            get {
                return ResourceManager.GetString("PS_CleanInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting files. Some files were not deleted!.
        /// </summary>
        internal static string PS_CleanupErr {
            get {
                return ResourceManager.GetString("PS_CleanupErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean selected {0}?.
        /// </summary>
        internal static string PS_CleanupExecuteQ {
            get {
                return ResourceManager.GetString("PS_CleanupExecuteQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean {0}?.
        /// </summary>
        internal static string PS_CleanupFull {
            get {
                return ResourceManager.GetString("PS_CleanupFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup was successfully completed!.
        /// </summary>
        internal static string PS_CleanupSuccess {
            get {
                return ResourceManager.GetString("PS_CleanupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform the cleanup?.
        /// </summary>
        internal static string PS_ExecuteMSG {
            get {
                return ResourceManager.GetString("PS_ExecuteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can free up to {0} hard-disk space after cleanup..
        /// </summary>
        internal static string PS_FrFInfo {
            get {
                return ResourceManager.GetString("PS_FrFInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup is not required..
        /// </summary>
        internal static string PS_LoadErr {
            get {
                return ResourceManager.GetString("PS_LoadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose the wrong language Steam from the dropdown list, so we will use English!.
        /// </summary>
        internal static string PS_NoLangSelected {
            get {
                return ResourceManager.GetString("PS_NoLangSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not choose! Please select at least one of the options of cleaning and run the cleanup again!.
        /// </summary>
        internal static string PS_NothingSelected {
            get {
                return ResourceManager.GetString("PS_NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting cleanup....
        /// </summary>
        internal static string PS_ProcessPrepare {
            get {
                return ResourceManager.GetString("PS_ProcessPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam has been successfully terminated..
        /// </summary>
        internal static string PS_ProcessTerminated {
            get {
                return ResourceManager.GetString("PS_ProcessTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating backup....
        /// </summary>
        internal static string PS_ProgressArchive {
            get {
                return ResourceManager.GetString("PS_ProgressArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup in progress....
        /// </summary>
        internal static string PS_ProgressCleanup {
            get {
                return ResourceManager.GetString("PS_ProgressCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string PS_ProgressFinished {
            get {
                return ResourceManager.GetString("PS_ProgressFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore factory game settings? This will remove all non-standard and old files and settings stored in Windows registry..
        /// </summary>
        internal static string PS_ResetSettingsMsg {
            get {
                return ResourceManager.GetString("PS_ResetSettingsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files for cleanup is not selected! Please select files and try again later..
        /// </summary>
        internal static string PS_SelectItemsMsg {
            get {
                return ResourceManager.GetString("PS_SelectItemsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup completed successfully. Steam will run in recovery mode right now!.
        /// </summary>
        internal static string PS_SeqCompleted {
            get {
                return ResourceManager.GetString("PS_SeqCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam client is running! To execute this cleanup please close it..
        /// </summary>
        internal static string PS_SteamRunning {
            get {
                return ResourceManager.GetString("PS_SteamRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during file installation. Please try again later!.
        /// </summary>
        internal static string QI_Excpt {
            get {
                return ResourceManager.GetString("QI_Excpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate VMT file automatically?.
        /// </summary>
        internal static string QI_GenVMTMsg {
            get {
                return ResourceManager.GetString("QI_GenVMTMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation completed successfully!.
        /// </summary>
        internal static string QI_InstSuccessfull {
            get {
                return ResourceManager.GetString("QI_InstSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file before pressing this button and try again!.
        /// </summary>
        internal static string QI_InstUnav {
            get {
                return ResourceManager.GetString("QI_InstUnav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string RPB_CloseCpt {
            get {
                return ResourceManager.GetString("RPB_CloseCpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed report with the name {0} has been successfully created! Now we will open the directory with generated report file in order that you can upload it to technical support service..
        /// </summary>
        internal static string RPB_ComprGen {
            get {
                return ResourceManager.GetString("RPB_ComprGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working... Please wait..
        /// </summary>
        internal static string RPB_CptWrk {
            get {
                return ResourceManager.GetString("RPB_CptWrk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report with the name {0} has been successfully created! Now we will open the directory with generated report file in order that you can upload it to technical support service..
        /// </summary>
        internal static string RPB_Generated {
            get {
                return ResourceManager.GetString("RPB_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Unable to execute tool Microsoft System Information. Perhaps it is not installed on this operating system. Creating a report is impossible..
        /// </summary>
        internal static string RPB_GenException {
            get {
                return ResourceManager.GetString("RPB_GenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate report now?.
        /// </summary>
        internal static string RPB_GenQst {
            get {
                return ResourceManager.GetString("RPB_GenQst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process will take a lot of time. Please be patient!.
        /// </summary>
        internal static string RPB_GenWarn {
            get {
                return ResourceManager.GetString("RPB_GenWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during files removal. Some files were not deleted..
        /// </summary>
        internal static string RW_RmException {
            get {
                return ResourceManager.GetString("RW_RmException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To work correctly, this programm needs {0} to be shut down. Proceed?.
        /// </summary>
        internal static string ST_KillMessage {
            get {
                return ResourceManager.GetString("ST_KillMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam login was successfully changed. Let&apos;s continue to work with the new one....
        /// </summary>
        internal static string StatusLoginChanged {
            get {
                return ResourceManager.GetString("StatusLoginChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All systems are working normally..
        /// </summary>
        internal static string StatusNormal {
            get {
                return ResourceManager.GetString("StatusNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened file in Config Editor: {0}..
        /// </summary>
        internal static string StatusOpenedFile {
            get {
                return ResourceManager.GetString("StatusOpenedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select game from the list!.
        /// </summary>
        internal static string StatusSApp {
            get {
                return ResourceManager.GetString("StatusSApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your Steam login from the list!.
        /// </summary>
        internal static string StatusSLogin {
            get {
                return ResourceManager.GetString("StatusSLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Cloud settings was successfully changed!.
        /// </summary>
        internal static string SteamCloudChanged {
            get {
                return ResourceManager.GetString("SteamCloudChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        internal static string SteamCloudStatusOff {
            get {
                return ResourceManager.GetString("SteamCloudStatusOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        internal static string SteamCloudStatusOn {
            get {
                return ResourceManager.GetString("SteamCloudStatusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You refused to enter your login Steam, so the work program is impossible. Restart this program later and enter the correct login!.
        /// </summary>
        internal static string SteamLoginCancel {
            get {
                return ResourceManager.GetString("SteamLoginCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Steam login:.
        /// </summary>
        internal static string SteamLoginEnterText {
            get {
                return ResourceManager.GetString("SteamLoginEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Steam login.
        /// </summary>
        internal static string SteamLoginEnterTitle {
            get {
                return ResourceManager.GetString("SteamLoginEnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Source Repair was unable to get a list of active logins Steam, so you have to enter it manually..
        /// </summary>
        internal static string SteamLoginsNotDetected {
            get {
                return ResourceManager.GetString("SteamLoginsNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured! Unable to locate user folders inside SteamApps. Start at least one supported game from Steam and restart this program..
        /// </summary>
        internal static string SteamNoLoginsDetected {
            get {
                return ResourceManager.GetString("SteamNoLoginsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Invalid characters detected in Steam path. Steam and the games will not work correctly. Reinstall Steam to folder, the path to which will contain only latin symbols..
        /// </summary>
        internal static string SteamNonASCIIDetected {
            get {
                return ResourceManager.GetString("SteamNonASCIIDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam installed correctly: Steam directory path does not contain illegal characters..
        /// </summary>
        internal static string SteamNonASCIINotDetected {
            get {
                return ResourceManager.GetString("SteamNonASCIINotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry keys related to Steam is not found. You do not need their cleaning. Click OK to exit the program!.
        /// </summary>
        internal static string SteamNotDetected {
            get {
                return ResourceManager.GetString("SteamNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You refused to enter the path to Steam, so the program will be terminated!.
        /// </summary>
        internal static string SteamPathCancel {
            get {
                return ResourceManager.GetString("SteamPathCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered the wrong path! The program will be terminated..
        /// </summary>
        internal static string SteamPathEnterErr {
            get {
                return ResourceManager.GetString("SteamPathEnterErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the path to Steam:.
        /// </summary>
        internal static string SteamPathEnterText {
            get {
                return ResourceManager.GetString("SteamPathEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the path to Steam.
        /// </summary>
        internal static string SteamPathEnterTitle {
            get {
                return ResourceManager.GetString("SteamPathEnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Critical error occured: can not get the path to the Steam from the registry, so you&apos;ll have to manually specify the correct path!.
        /// </summary>
        internal static string SteamPathNotDetected {
            get {
                return ResourceManager.GetString("SteamPathNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed.cfg.
        /// </summary>
        internal static string UnnamedFileName {
            get {
                return ResourceManager.GetString("UnnamedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates detected. Your application is up to date..
        /// </summary>
        internal static string UPD_AppNoUpdates {
            get {
                return ResourceManager.GetString("UPD_AppNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application update available. New version: {0}..
        /// </summary>
        internal static string UPD_AppUpdateAvail {
            get {
                return ResourceManager.GetString("UPD_AppUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates detected. SRC Repair is using latest version of game database..
        /// </summary>
        internal static string UPD_DbNoUpdates {
            get {
                return ResourceManager.GetString("UPD_DbNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database update available. New version: {0}..
        /// </summary>
        internal static string UPD_DbUpdateAvail {
            get {
                return ResourceManager.GetString("UPD_DbUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to download updates! Allow the program to get data from the Internet and try again later..
        /// </summary>
        internal static string UPD_DownloadException {
            get {
                return ResourceManager.GetString("UPD_DownloadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking for updates! Allow the program to get data from the Internet and try again later..
        /// </summary>
        internal static string UPD_ExceptionDetected {
            get {
                return ResourceManager.GetString("UPD_ExceptionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice: Hash of existing file {0}: {1}..
        /// </summary>
        internal static string UPD_ExtHashSum {
            get {
                return ResourceManager.GetString("UPD_ExtHashSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is not required because you have the latest version of the game database..
        /// </summary>
        internal static string UPD_GamL_Latest {
            get {
                return ResourceManager.GetString("UPD_GamL_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game database has been updated successfully. Restart this program..
        /// </summary>
        internal static string UPD_GamL_Updated {
            get {
                return ResourceManager.GetString("UPD_GamL_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is not required because you have the latest version of the HUD database..
        /// </summary>
        internal static string UPD_HUDDb_Latest {
            get {
                return ResourceManager.GetString("UPD_HUDDb_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HUD database has been updated successfully. Restart this program..
        /// </summary>
        internal static string UPD_HUDDb_Updated {
            get {
                return ResourceManager.GetString("UPD_HUDDb_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates detected. SRC Repair is using latest version of HUD database..
        /// </summary>
        internal static string UPD_HUDNoUpdates {
            get {
                return ResourceManager.GetString("UPD_HUDNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD database update available. New version: {0}..
        /// </summary>
        internal static string UPD_HUDUpdateAvail {
            get {
                return ResourceManager.GetString("UPD_HUDUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is not required because you have the latest version of the program..
        /// </summary>
        internal static string UPD_LatestInstalled {
            get {
                return ResourceManager.GetString("UPD_LatestInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game database has been updated successfully..
        /// </summary>
        internal static string UPD_ProcFinMsg {
            get {
                return ResourceManager.GetString("UPD_ProcFinMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the game database from server....
        /// </summary>
        internal static string UPD_ProcStartMsg {
            get {
                return ResourceManager.GetString("UPD_ProcStartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice: Received server hash of the game database {0}..
        /// </summary>
        internal static string UPD_RecvHashStr {
            get {
                return ResourceManager.GetString("UPD_RecvHashStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to run installer. The program has not been updated. Run the update again later!.
        /// </summary>
        internal static string UPD_UpdateFailure {
            get {
                return ResourceManager.GetString("UPD_UpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version has been successfully received from server. We will install it now!.
        /// </summary>
        internal static string UPD_UpdateSuccessful {
            get {
                return ResourceManager.GetString("UPD_UpdateSuccessful", resourceCulture);
            }
        }
    }
}
