//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srcrepair.gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebugStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("srcrepair.gui.DebugStrings", typeof(DebugStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during unpacking files from Zip archives..
        /// </summary>
        internal static string AppDbgExArWrkUnpack {
            get {
                return ResourceManager.GetString("AppDbgExArWrkUnpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove selected backups..
        /// </summary>
        internal static string AppDbgExBackupRem {
            get {
                return ResourceManager.GetString("AppDbgExBackupRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while checking for updates during application startup..
        /// </summary>
        internal static string AppDbgExBgWChk {
            get {
                return ResourceManager.GetString("AppDbgExBgWChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create graphical settings backup of all games..
        /// </summary>
        internal static string AppDbgExBkAllGames {
            get {
                return ResourceManager.GetString("AppDbgExBkAllGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create backup of all Steam settings stored in registry..
        /// </summary>
        internal static string AppDbgExBkAllStm {
            get {
                return ResourceManager.GetString("AppDbgExBkAllStm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to load backup file in text editor..
        /// </summary>
        internal static string AppDbgExBkExtEdt {
            get {
                return ResourceManager.GetString("AppDbgExBkExtEdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to show selected backup file in file manager..
        /// </summary>
        internal static string AppDbgExBkFMan {
            get {
                return ResourceManager.GetString("AppDbgExBkFMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to save auto backup before saving game settings..
        /// </summary>
        internal static string AppDbgExBkGsAuto {
            get {
                return ResourceManager.GetString("AppDbgExBkGsAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create graphical settings backup of selected game..
        /// </summary>
        internal static string AppDbgExBkSg {
            get {
                return ResourceManager.GetString("AppDbgExBkSg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to open web browser to open bug tracker URL..
        /// </summary>
        internal static string AppDbgExBugRep {
            get {
                return ResourceManager.GetString("AppDbgExBugRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to save config auto backup before saving it in Config editor..
        /// </summary>
        internal static string AppDbgExCfgEdAutoBackup {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdAutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create manual backup of config file..
        /// </summary>
        internal static string AppDbgExCfgEdBkMan {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdBkMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to copy item to clipboard in Config editor..
        /// </summary>
        internal static string AppDbgExCfgEdCopy {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to cut item to clipboard in Config editor..
        /// </summary>
        internal static string AppDbgExCfgEdCut {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to load config file in text editor..
        /// </summary>
        internal static string AppDbgExCfgEdExtEdt {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdExtEdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while reading config file in Config editor..
        /// </summary>
        internal static string AppDbgExCfgEdLoad {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to paste item from clipboard in Config editor..
        /// </summary>
        internal static string AppDbgExCfgEdPaste {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to remove item in Config editor..
        /// </summary>
        internal static string AppDbgExCfgEdRemRow {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdRemRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during saving file in Config editor..
        /// </summary>
        internal static string AppDbgExCfgEdSave {
            get {
                return ResourceManager.GetString("AppDbgExCfgEdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during FPS config selection (click on warning icon)..
        /// </summary>
        internal static string AppDbgExCfgSelection {
            get {
                return ResourceManager.GetString("AppDbgExCfgSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while cleaning up Steam blob files..
        /// </summary>
        internal static string AppDbgExClnBlobs {
            get {
                return ResourceManager.GetString("AppDbgExClnBlobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while cleaning up empty directories..
        /// </summary>
        internal static string AppDbgExClnEmptyDirs {
            get {
                return ResourceManager.GetString("AppDbgExClnEmptyDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to show selected file in file manager..
        /// </summary>
        internal static string AppDbgExClnFm {
            get {
                return ResourceManager.GetString("AppDbgExClnFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while removing files from queue..
        /// </summary>
        internal static string AppDbgExClnQueueRun {
            get {
                return ResourceManager.GetString("AppDbgExClnQueueRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while cleaning up Steam registry entries..
        /// </summary>
        internal static string AppDbgExClnReg {
            get {
                return ResourceManager.GetString("AppDbgExClnReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during FPS config installation..
        /// </summary>
        internal static string AppDbgExFpsInstall {
            get {
                return ResourceManager.GetString("AppDbgExFpsInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while compressing files as backup before installation of new FPS config..
        /// </summary>
        internal static string AppDbgExFpsInstBackup {
            get {
                return ResourceManager.GetString("AppDbgExFpsInstBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during FPS config uninstallation..
        /// </summary>
        internal static string AppDbgExFpsUninstall {
            get {
                return ResourceManager.GetString("AppDbgExFpsUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while removing HUD archive file..
        /// </summary>
        internal static string AppDbgExHudArchRem {
            get {
                return ResourceManager.GetString("AppDbgExHudArchRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to show selected HUD directory in file manager..
        /// </summary>
        internal static string AppDbgExHudExtFm {
            get {
                return ResourceManager.GetString("AppDbgExHudExtFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during HUD installation..
        /// </summary>
        internal static string AppDbgExHUDInstall {
            get {
                return ResourceManager.GetString("AppDbgExHUDInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to select another HUD..
        /// </summary>
        internal static string AppDbgExHudSelect {
            get {
                return ResourceManager.GetString("AppDbgExHudSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while running installation of selected file..
        /// </summary>
        internal static string AppDbgExInstRun {
            get {
                return ResourceManager.GetString("AppDbgExInstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disable both WIN keys..
        /// </summary>
        internal static string AppDbgExKbBW {
            get {
                return ResourceManager.GetString("AppDbgExKbBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disable both WIN and CONTEXT keys..
        /// </summary>
        internal static string AppDbgExKbBWCtx {
            get {
                return ResourceManager.GetString("AppDbgExKbBWCtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disable left WIN key..
        /// </summary>
        internal static string AppDbgExKbLW {
            get {
                return ResourceManager.GetString("AppDbgExKbLW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disable all custom key overrides..
        /// </summary>
        internal static string AppDbgExKbRestore {
            get {
                return ResourceManager.GetString("AppDbgExKbRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to disable right WIN and CONTEXT keys..
        /// </summary>
        internal static string AppDbgExKbRWCtx {
            get {
                return ResourceManager.GetString("AppDbgExKbRWCtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while cleaning up debug log file..
        /// </summary>
        internal static string AppDbgExLvClean {
            get {
                return ResourceManager.GetString("AppDbgExLvClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to load current debug log file..
        /// </summary>
        internal static string AppDbgExLvLoad {
            get {
                return ResourceManager.GetString("AppDbgExLvLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to save blacklist auto backup before saving it..
        /// </summary>
        internal static string AppDbgExMMAutoSave {
            get {
                return ResourceManager.GetString("AppDbgExMMAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while reading muted users database..
        /// </summary>
        internal static string AppDbgExMMReadDb {
            get {
                return ResourceManager.GetString("AppDbgExMMReadDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while writing to save muted users database..
        /// </summary>
        internal static string AppDbgExMMSaveDb {
            get {
                return ResourceManager.GetString("AppDbgExMMSaveDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on trying to launch Windows registry editor to restore saved registry file..
        /// </summary>
        internal static string AppDbgExRegedit {
            get {
                return ResourceManager.GetString("AppDbgExRegedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during removal of game settings..
        /// </summary>
        internal static string AppDbgExRemVd {
            get {
                return ResourceManager.GetString("AppDbgExRemVd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to save configs auto backup before removing game settings..
        /// </summary>
        internal static string AppDbgExRemVdAutoCfg {
            get {
                return ResourceManager.GetString("AppDbgExRemVdAutoCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to save video auto backup before removing game settings..
        /// </summary>
        internal static string AppDbgExRemVdAutoGs {
            get {
                return ResourceManager.GetString("AppDbgExRemVdAutoGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to show generated report file in file manager..
        /// </summary>
        internal static string AppDbgExRepFm {
            get {
                return ResourceManager.GetString("AppDbgExRepFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while generating report..
        /// </summary>
        internal static string AppDbgExRepGen {
            get {
                return ResourceManager.GetString("AppDbgExRepGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to pack all generated logs to a single Zip archive..
        /// </summary>
        internal static string AppDbgExRepPack {
            get {
                return ResourceManager.GetString("AppDbgExRepPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepGen Worker is busy. Can&apos;t start build sequence..
        /// </summary>
        internal static string AppDbgExRepWrkBusy {
            get {
                return ResourceManager.GetString("AppDbgExRepWrkBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while removing files..
        /// </summary>
        internal static string AppDbgExRmRf {
            get {
                return ResourceManager.GetString("AppDbgExRmRf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory report was not created..
        /// </summary>
        internal static string AppDbgExRpMdrNotCreated {
            get {
                return ResourceManager.GetString("AppDbgExRpMdrNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while handling selected game by user or application..
        /// </summary>
        internal static string AppDbgExSelGame {
            get {
                return ResourceManager.GetString("AppDbgExSelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to get Steam path. Application will be terminated..
        /// </summary>
        internal static string AppDbgExSteamPath {
            get {
                return ResourceManager.GetString("AppDbgExSteamPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while initializing SteamManager class instance..
        /// </summary>
        internal static string AppDbgExStmmInit {
            get {
                return ResourceManager.GetString("AppDbgExStmmInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while filling Graphic tweaker for Type1 game..
        /// </summary>
        internal static string AppDbgExT1LoadFail {
            get {
                return ResourceManager.GetString("AppDbgExT1LoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to save Type1 graphical settings..
        /// </summary>
        internal static string AppDbgExT1SaveFail {
            get {
                return ResourceManager.GetString("AppDbgExT1SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to save auto backup before saving Type2 game settings..
        /// </summary>
        internal static string AppDbgExT2AutoFail {
            get {
                return ResourceManager.GetString("AppDbgExT2AutoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while filling Graphic tweaker for Type2 game..
        /// </summary>
        internal static string AppDbgExT2LoadFail {
            get {
                return ResourceManager.GetString("AppDbgExT2LoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to save Type2 graphical settings..
        /// </summary>
        internal static string AppDbgExT2SaveFail {
            get {
                return ResourceManager.GetString("AppDbgExT2SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to install binary update..
        /// </summary>
        internal static string AppDbgExUpdBinInst {
            get {
                return ResourceManager.GetString("AppDbgExUpdBinInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to install XML database update..
        /// </summary>
        internal static string AppDbgExUpdXmlDbInst {
            get {
                return ResourceManager.GetString("AppDbgExUpdXmlDbInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to open web browser to show cvarlist..
        /// </summary>
        internal static string AppDbgExUrlCvList {
            get {
                return ResourceManager.GetString("AppDbgExUrlCvList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to open web browser to show Steam group profile..
        /// </summary>
        internal static string AppDbgExUrlGroup {
            get {
                return ResourceManager.GetString("AppDbgExUrlGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to open web browser to show app commentary page..
        /// </summary>
        internal static string AppDbgExUrlHome {
            get {
                return ResourceManager.GetString("AppDbgExUrlHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to open web browser to show HUD&apos;s homepage..
        /// </summary>
        internal static string AppDbgExUrlHudHome {
            get {
                return ResourceManager.GetString("AppDbgExUrlHudHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to open web browser to show Steam profile..
        /// </summary>
        internal static string AppDbgExUrlStmSel {
            get {
                return ResourceManager.GetString("AppDbgExUrlStmSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during new UserID selection..
        /// </summary>
        internal static string AppDbgExUserIdSel {
            get {
                return ResourceManager.GetString("AppDbgExUserIdSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on trying to launch Steam to validate game cache..
        /// </summary>
        internal static string AppDbgExValCache {
            get {
                return ResourceManager.GetString("AppDbgExValCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on parsing XML game database. Application will be terminated..
        /// </summary>
        internal static string AppDbgExXmlParse {
            get {
                return ResourceManager.GetString("AppDbgExXmlParse", resourceCulture);
            }
        }
    }
}
