//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srcrepair.gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("srcrepair.gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/xvitaly/srcrepair/issues/new.
        /// </summary>
        internal static string AppBtURL {
            get {
                return ResourceManager.GetString("AppBtURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wget.
        /// </summary>
        internal static string AppDnlUA {
            get {
                return ResourceManager.GetString("AppDnlUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srcrepair_{0}.chm.
        /// </summary>
        internal static string AppHelpFileName {
            get {
                return ResourceManager.GetString("AppHelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kbhelper.exe.
        /// </summary>
        internal static string AppKBHelperBin {
            get {
                return ResourceManager.GetString("AppKBHelperBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRC Repair.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.easycoding.org/projects/srcrepair#respond.
        /// </summary>
        internal static string AppURLReply {
            get {
                return ResourceManager.GetString("AppURLReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam://url/GroupSteamIDPage/103582791431662552.
        /// </summary>
        internal static string AppURLSteamGrID {
            get {
                return ResourceManager.GetString("AppURLSteamGrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://steamcommunity.com/groups/srcrepair.
        /// </summary>
        internal static string AppURLSteamGroup {
            get {
                return ResourceManager.GetString("AppURLSteamGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string BU_PrefixCfg {
            get {
                return ResourceManager.GetString("BU_PrefixCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string BU_PrefixDef {
            get {
                return ResourceManager.GetString("BU_PrefixDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceBan.
        /// </summary>
        internal static string BU_PrefixVChat {
            get {
                return ResourceManager.GetString("BU_PrefixVChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoAutoCfg.
        /// </summary>
        internal static string BU_PrefixVidAuto {
            get {
                return ResourceManager.GetString("BU_PrefixVidAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoCfg.
        /// </summary>
        internal static string BU_PrefixVideo {
            get {
                return ResourceManager.GetString("BU_PrefixVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string BU_TablePrefix {
            get {
                return ResourceManager.GetString("BU_TablePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srcrepair.gui.CVList.
        /// </summary>
        internal static string CE_CVResDf {
            get {
                return ResourceManager.GetString("CE_CVResDf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconAdd {
            get {
                object obj = ResourceManager.GetObject("IconAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconArrow {
            get {
                object obj = ResourceManager.GetObject("IconArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconBackUp {
            get {
                object obj = ResourceManager.GetObject("IconBackUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconBug {
            get {
                object obj = ResourceManager.GetObject("IconBug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconClean {
            get {
                object obj = ResourceManager.GetObject("IconClean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconConvert {
            get {
                object obj = ResourceManager.GetObject("IconConvert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconCopy {
            get {
                object obj = ResourceManager.GetObject("IconCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconCut {
            get {
                object obj = ResourceManager.GetObject("IconCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconDelete {
            get {
                object obj = ResourceManager.GetObject("IconDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconExit {
            get {
                object obj = ResourceManager.GetObject("IconExit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconGlobe {
            get {
                object obj = ResourceManager.GetObject("IconGlobe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconGreenCircle {
            get {
                object obj = ResourceManager.GetObject("IconGreenCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconHelp {
            get {
                object obj = ResourceManager.GetObject("IconHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconHome {
            get {
                object obj = ResourceManager.GetObject("IconHome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconInfo {
            get {
                object obj = ResourceManager.GetObject("IconInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconInstaller {
            get {
                object obj = ResourceManager.GetObject("IconInstaller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconKeyboard {
            get {
                object obj = ResourceManager.GetObject("IconKeyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconMHint {
            get {
                object obj = ResourceManager.GetObject("IconMHint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconMute {
            get {
                object obj = ResourceManager.GetObject("IconMute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconNew {
            get {
                object obj = ResourceManager.GetObject("IconNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconNotebook {
            get {
                object obj = ResourceManager.GetObject("IconNotebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconOpen {
            get {
                object obj = ResourceManager.GetObject("IconOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconOptions {
            get {
                object obj = ResourceManager.GetObject("IconOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconPaste {
            get {
                object obj = ResourceManager.GetObject("IconPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconRedCircle {
            get {
                object obj = ResourceManager.GetObject("IconRedCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconRefresh {
            get {
                object obj = ResourceManager.GetObject("IconRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconReport {
            get {
                object obj = ResourceManager.GetObject("IconReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconRestore {
            get {
                object obj = ResourceManager.GetObject("IconRestore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconSave {
            get {
                object obj = ResourceManager.GetObject("IconSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconSaveAs {
            get {
                object obj = ResourceManager.GetObject("IconSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconSearch {
            get {
                object obj = ResourceManager.GetObject("IconSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconSourceEngine {
            get {
                object obj = ResourceManager.GetObject("IconSourceEngine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconSteam {
            get {
                object obj = ResourceManager.GetObject("IconSteam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTextEditor {
            get {
                object obj = ResourceManager.GetObject("IconTextEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconUpdateAvailable {
            get {
                object obj = ResourceManager.GetObject("IconUpdateAvailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconUpdateChecking {
            get {
                object obj = ResourceManager.GetObject("IconUpdateChecking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconUpdateError {
            get {
                object obj = ResourceManager.GetObject("IconUpdateError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconUpdateNotAvailable {
            get {
                object obj = ResourceManager.GetObject("IconUpdateNotAvailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconWarning {
            get {
                object obj = ResourceManager.GetObject("IconWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageAppLogo {
            get {
                object obj = ResourceManager.GetObject("ImageAppLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageLoadingFile {
            get {
                object obj = ResourceManager.GetObject("ImageLoadingFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageXmas {
            get {
                object obj = ResourceManager.GetObject("ImageXmas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://steamcommunity.com/profiles/{0}/.
        /// </summary>
        internal static string MM_CommunityURL {
            get {
                return ResourceManager.GetString("MM_CommunityURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^STEAM_0:[01]:[0-9]{1,9}$.
        /// </summary>
        internal static string MM_SteamID32Regex {
            get {
                return ResourceManager.GetString("MM_SteamID32Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (STEAM_[0-9]:[0-9]:[0-9]+|\[U:[0-9]:[0-9]+\]).
        /// </summary>
        internal static string MM_SteamIDRegex {
            get {
                return ResourceManager.GetString("MM_SteamIDRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[0-9a-zA-Z]*$.
        /// </summary>
        internal static string MO_CustomDirRegex {
            get {
                return ResourceManager.GetString("MO_CustomDirRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srcrepair.gui.Resources.TemplateVMTSpray.txt.
        /// </summary>
        internal static string PI_TemplateFile {
            get {
                return ResourceManager.GetString("PI_TemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;UnlitGeneric&quot;
        ///{
        ///	&quot;$basetexture&quot;	&quot;{D}&quot;
        ///	&quot;$translucent&quot; &quot;1&quot;
        ///	&quot;$ignorez&quot; &quot;1&quot;
        ///	&quot;$vertexcolor&quot; &quot;1&quot;
        ///	&quot;$vertexalpha&quot; &quot;1&quot;
        ///}
        ///.
        /// </summary>
        internal static string TemplateVMTSpray {
            get {
                return ResourceManager.GetString("TemplateVMTSpray", resourceCulture);
            }
        }
    }
}
