//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srcrepair.core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("srcrepair.core.ReportStrings", typeof(ReportStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmd.exe.
        /// </summary>
        internal static string CmdIntExe {
            get {
                return ResourceManager.GetString("CmdIntExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reports.
        /// </summary>
        internal static string DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dxdiag.exe.
        /// </summary>
        internal static string DxDiagExe {
            get {
                return ResourceManager.GetString("DxDiagExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dxdiag_{0}.log.
        /// </summary>
        internal static string DxDiagOutput {
            get {
                return ResourceManager.GetString("DxDiagOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /t {0}.
        /// </summary>
        internal static string DxDiagParams {
            get {
                return ResourceManager.GetString("DxDiagParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        internal static string GenericArchDirectory {
            get {
                return ResourceManager.GetString("GenericArchDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipconfig_{0}.log.
        /// </summary>
        internal static string IpConfigOutput {
            get {
                return ResourceManager.GetString("IpConfigOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /C ipconfig /all &gt; &quot;{0}&quot;.
        /// </summary>
        internal static string IpConfigParams {
            get {
                return ResourceManager.GetString("IpConfigParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report.
        /// </summary>
        internal static string MsInfoArchDirectory {
            get {
                return ResourceManager.GetString("MsInfoArchDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msinfo32.exe.
        /// </summary>
        internal static string MsInfoExe {
            get {
                return ResourceManager.GetString("MsInfoExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report_{0}.txt.
        /// </summary>
        internal static string MsInfoOutput {
            get {
                return ResourceManager.GetString("MsInfoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /report &quot;{0}&quot;.
        /// </summary>
        internal static string MsInfoParams {
            get {
                return ResourceManager.GetString("MsInfoParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to netstat_{0}.log.
        /// </summary>
        internal static string NetStatOutput {
            get {
                return ResourceManager.GetString("NetStatOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /C netstat -a &gt; &quot;{0}&quot;.
        /// </summary>
        internal static string NetStatParams {
            get {
                return ResourceManager.GetString("NetStatParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ping_{0}.log.
        /// </summary>
        internal static string PingScOutput {
            get {
                return ResourceManager.GetString("PingScOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /C ping steampowered.com &gt; &quot;{0}&quot;.
        /// </summary>
        internal static string PingScParams {
            get {
                return ResourceManager.GetString("PingScParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to routing_{0}.log.
        /// </summary>
        internal static string RoutesOutput {
            get {
                return ResourceManager.GetString("RoutesOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /C route print &gt; &quot;{0}&quot;.
        /// </summary>
        internal static string RoutesParams {
            get {
                return ResourceManager.GetString("RoutesParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traceroute_{0}.log.
        /// </summary>
        internal static string TracertScOutput {
            get {
                return ResourceManager.GetString("TracertScOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /C tracert steampowered.com &gt; &quot;{0}&quot;.
        /// </summary>
        internal static string TracertScParams {
            get {
                return ResourceManager.GetString("TracertScParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users_{0}.log.
        /// </summary>
        internal static string UsersOutput {
            get {
                return ResourceManager.GetString("UsersOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /C net user &gt; &quot;{0}&quot;.
        /// </summary>
        internal static string UsersParams {
            get {
                return ResourceManager.GetString("UsersParams", resourceCulture);
            }
        }
    }
}
